<?php


return [
    /*
    |--------------------------------------------------------------------------
    | Local domain
    |--------------------------------------------------------------------------
    |
    | By default, selects a free address and port.
    |
    */

    'uri' => 8080,


    /*
    |--------------------------------------------------------------------------
    | Distinguished Name
    |--------------------------------------------------------------------------
    |
    | Should be set to a private key that was
    | previously generated by openssl_pkey_new (or otherwise obtained from
    | the other openssl_pkey family of functions). The corresponding public
    | portion of the key will be used to sign the CSR.
    |
    */

    'dm' => [
        'countryName'            => 'RU',
        'stateOrProvinceName'    => 'Lipetsk',
        'localityName'           => 'Sajya',
        'organizationName'       => 'The Sajya Limited',
        'organizationalUnitName' => 'PHP Sajya Team',
        'commonName'             => 'Alexandr Chernyhaev',
        'emailAddress'           => 'tabuna@example.com',
    ],

    /*
    |--------------------------------------------------------------------------
    | Key generation parameters
    |--------------------------------------------------------------------------
    |
    | Settings options available see
    |
    | https://www.php.net/manual/en/function.openssl-csr-new.php
    |
    */

    'key' => [
        'private_key_bits' => 2048,
        'private_key_type' => OPENSSL_KEYTYPE_RSA,
    ],

    /*
    |--------------------------------------------------------------------------
    | Certificate Signing Request
    |--------------------------------------------------------------------------
    |
    | Settings options available see
    |
    | https://www.php.net/manual/en/function.openssl-csr-new.php
    |
    */

    'csr' => [
        'digest_alg' => 'sha256'
    ]
];